# Generated by Django 5.1.6 on 2025-02-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={}, max_length=20, unique=True),
        ),
    ]
